Model changes and dashboard design integration.
Promact/testcase-management-suite pull request #16
Opened 2017-03-28 12:09 UTC by Krunal-Promact

2017-03-29 04:58 UTC, chintans requested changes

2017-03-29 04:58 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/DataContext/TestCaseManagementDbContext.cs
>              ChangeTracker.Entries().Where(x => x.Entity is TestCaseManagementBase && x.State == EntityState.Added).ToList().ForEach(x =>
Here after using Where extension method. Why have you used ToList and then ForEach?

2017-03-29 04:58 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/DataContext/TestCaseManagementDbContext.cs
>              ChangeTracker.Entries().Where(x => x.Entity is TestCaseManagementBase && x.State == EntityState.Added).ToList().ForEach(x =>
Even in Async method all code is written synchronously. It is not right

2017-03-29 04:58 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Models/Module/Module.cs
> +        public virtual Project.Project Project { get; set; }
Only use Class name. Don't use Namespaces here

2017-03-29 04:58 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Models/Module/ModuleTestCaseMapping.cs
>          public virtual TestCase.TestCase TestCase { get; set; }
same as above. Use only class name and not with namespace

2017-03-29 04:58 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Models/Project/Project.cs
> +        public virtual ICollection<Module.Module> Module { get; set; }
Same as above

2017-03-29 04:58 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Models/Project/Project.cs
> +        public virtual ICollection<Scenario.Scenario> Scenario { get; set; }
Same as above

2017-03-29 04:58 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Models/Scenario/Scenario.cs
> +        public virtual Project.Project Project { get; set; }
You have not added ForeignKey attribute here

2017-03-29 04:58 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Models/Scenario/ScenarioTestCaseMapping.cs
>          public virtual TestCase.TestCase TestCase { get; set; }
Only class name

2017-03-29 04:58 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Models/TestCase/Base/TestCaseBase.cs
> +        public virtual UserInfo CreatedUser { get; set; }
CreatedBy is string, How does it map to CreatedUser?

2017-03-29 04:58 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Enums/Condition.cs
> +        PreCondition,
I think there is still confusion with Pre-Condition and Post-Condition.

Pre-Condition can have 
1. Previous test case as a condition
2. Simple string
3. Mixture of both

Post-Condition will have only string value nothing else. according to that there is no similarity between Pre-Condition and Post-Condition.

2017-03-29 06:20 UTC, Krunal-Promact commented on src/Promact.TestCaseManagement.DomainModel/DataContext/TestCaseManagementDbContext.cs
>              ChangeTracker.Entries().Where(x => x.Entity is TestCaseManagementBase && x.State == EntityState.Added).ToList().ForEach(x =>
After using Where extension method, I want to set CreatedDateTime for all entities being added. So for that purpose, i have to iterate on all entities. In order to iterate on all entities, i have to use for each loop which I can not use directly after Where extension method. so for that purpose, I have first used ToList extension method and then ForEach.

2017-03-29 06:20 UTC, Krunal-Promact commented on src/Promact.TestCaseManagement.DomainModel/DataContext/TestCaseManagementDbContext.cs
>              ChangeTracker.Entries().Where(x => x.Entity is TestCaseManagementBase && x.State == EntityState.Added).ToList().ForEach(x =>
Changes made. Please review it.

2017-03-29 06:20 UTC, Krunal-Promact commented on src/Promact.TestCaseManagement.DomainModel/Enums/Condition.cs
> +        PreCondition,
I had a discussion with the tester on Pre-Condition and Post Condition after your feedback. As per the examples that you have given in feedback, Tester suggested that there are also chances of having test cases in Post Conditions. So after having a discussion with the tester, i updated it accordingly. The current model configuration for Pre-Conditions and Post Conditions will satisfy requirement of having 
1. Test case as condition
2. Simple string
3. Mixture of both

2017-03-29 06:20 UTC, Krunal-Promact commented on src/Promact.TestCaseManagement.DomainModel/Models/Module/Module.cs
> +        public virtual Project.Project Project { get; set; }
Actually Project class is in Project folder. So I have to change namespace for it. If you agree with it then I will change namespace accordingly for all models.

2017-03-29 06:20 UTC, Krunal-Promact commented on src/Promact.TestCaseManagement.DomainModel/Models/Module/ModuleTestCaseMapping.cs
>          public virtual TestCase.TestCase TestCase { get; set; }
Same TestCase class is in TestCase folder. So I have to change namespace for it. If you agree with it then I will change namespace accordingly for all models.

2017-03-29 06:20 UTC, Krunal-Promact commented on src/Promact.TestCaseManagement.DomainModel/Models/Scenario/Scenario.cs
> +        public virtual Project.Project Project { get; set; }
As per the default convention of Entity Framework Core if my foreign key name prefix with its class name and ends with Id, I can explicitly avoid writing ForeignKey attribute to set the foreign key of the class.

2017-03-29 06:20 UTC, Krunal-Promact commented on src/Promact.TestCaseManagement.DomainModel/Models/TestCase/Base/TestCaseBase.cs
> +        public virtual UserInfo CreatedUser { get; set; }
UserInfo class has a primary key in a string that I am getting in claims after authenticating against OAuth server. So UserInfo class has a string as a primary key and here CreatedBy is the string as the foreign key.

2017-03-29 06:55 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Enums/Condition.cs
> +        PreCondition,
Ok, If you discuss requirement with someone other than me then you are suppose to convey that via email. I don't have an idea that you discussed something with someone else and that is why you have created model like this. If I had known requirement update I would have not spent much of the time reviewing it. It is very important that you keep me in a loop.

2017-03-29 06:55 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Enums/Condition.cs
> +        PreCondition,
I am fine with this requirement change

2017-03-29 07:01 UTC, chintans requested changes
There are inconsistency in using ForeignKey attribute.

You have used ForeignKey attribute in some of the class and in some you have omitted it. Please remove these inconsistency.

2017-03-29 07:11 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Models/Module/Module.cs
> +        public virtual Project.Project Project { get; set; }
Don't nest classes under module names. i.e, keep all class files under Modals only. No need to separate them

2017-04-04 08:26 UTC, chintans requested changes

2017-04-04 08:26 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Models/TestCaseBase.cs
> +        public string CreatedUserId { get; set; }
Is CreatedUserId a foreign key to CreatedUser? If yes, will it map it without ForeignKey attribute?

2017-04-04 08:26 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Models/TestCaseManagementBase.cs
> +        public bool IsDeleted { get; set; }
IsDeleted should be Nullable

2017-04-04 08:26 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Models/Module.cs
> +        public virtual Project Project { get; set; }
Same as above, will it map ProjectId without ForeignKey attributes?

2017-04-04 08:26 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Models/Project.cs
>          public bool IsActive { get; set; }
IsActive should be Nullable

2017-04-04 09:14 UTC, Krunal-Promact commented on src/Promact.TestCaseManagement.DomainModel/Models/Module.cs
> +        public virtual Project Project { get; set; }
Yes, it will map ProjectId without ForeignKey attribute as per the default convention.

2017-04-04 09:14 UTC, Krunal-Promact commented on src/Promact.TestCaseManagement.DomainModel/Models/Project.cs
>          public bool IsActive { get; set; }
It is a boolean value. I did not find any practical reason for making it nullable. Either Project will be active or not. There is not any third possibility. If I miss some point then please correct me on it.

2017-04-04 09:14 UTC, Krunal-Promact commented on src/Promact.TestCaseManagement.DomainModel/Models/TestCaseBase.cs
> +        public string CreatedUserId { get; set; }
Yes, CreatedUserId is a foreign key to CreatedUser and it will map without ForeignKey attribute.

2017-04-04 09:14 UTC, Krunal-Promact commented on src/Promact.TestCaseManagement.DomainModel/Models/TestCaseManagementBase.cs
> +        public bool IsDeleted { get; set; }
Same did not find any practical reason for making it nullable. Either project is deleted or not deleted at all. If i miss any point then please correct me.

2017-04-04 09:30 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Models/Project.cs
>          public bool IsActive { get; set; }
There are 3 states of the Nullable Boolean

1. Null - Which means false but does not occupy any storage space
2. true - which means condition is true
3. false - this value might never be entered or will be entered if deleted project is reactivated later.

So, as you can see Nullable makes sense in practical programming.

2017-04-05 04:49 UTC, Krunal-Promact commented
IsActive and IsDeleted flag made nullable.

2017-04-10 12:04 UTC, chintans requested changes

2017-04-10 12:04 UTC, chintans commented on src/Promact.TestCaseManagement.DomainModel/Enums/TeamRole.cs
>          TeamLeader,
TeamRole should not be enum. Role management is not part of test-case-management. It will come from oauth-server. should be handled using strings.

2017-04-13 03:39 UTC, chintans approved these changes

2017-04-13 03:39 UTC, merged