#22 implemented API for get all projects of users
Promact/testcase-management-suite pull request #24
Opened 2017-04-18 05:47 UTC by kinjalgor

2017-04-18 08:24 UTC, Krunal-Promact requested changes

2017-04-18 08:24 UTC, Krunal-Promact commented on src/Promact.TestCaseManagement.Core/Controllers/ProjectController.cs
> +                var userInfo = new UserInfo();
no need to create object.

2017-04-18 08:24 UTC, Krunal-Promact commented on src/Promact.TestCaseManagement.Core/Controllers/ProjectController.cs
> +                return Ok(await _iProjectRepository.GetProjectsAsync(userInfo.Id));
directly pass id of logged in user.

2017-04-19 07:06 UTC, Krunal-Promact approved these changes

2017-04-20 06:43 UTC, chintans requested changes

2017-04-20 06:43 UTC, chintans commented on src/Promact.TestCaseManagement.Core/Controllers/ProjectController.cs
> +                return Ok(await _iProjectRepository.GetProjectsAsync(User.Claims.ToList().Single(x => x.Type.Equals(StringConstants.Sub)).Value));
I am not sure why have you used ToList and then Single? It could have been only First. Overall the Lambda expression is to complex and not optimal

2017-04-20 06:43 UTC, chintans commented on src/Promact.TestCaseManagement.Core/Controllers/ProjectController.cs
> +            return Unauthorized();
I don't understand the point of returning Unauthorized. If an action is covered under [Authorize] attribute then there is no need for an unauthorized

2017-04-20 06:43 UTC, chintans commented on src/Promact.TestCaseManagement.Repository/ProjectRepository/ProjectRepository.cs
> +        public async Task<List<Project>> GetProjectsAsync(string userId)
We don't return List<> it is always IEnumerable<>

2017-04-20 10:44 UTC, Krunal-Promact commented
suggested changes completed. @chintans Please provide your feedback

2017-04-24 07:00 UTC, chintans approved these changes

2017-04-24 07:01 UTC, merged